# Generated by Django 4.1.7 on 2023-03-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='logo',
            field=models.FileField(default='settings.MEDIA_ROOT/sources_logos/source-default.svg', upload_to='sources_logos/'),
        ),
    ]
