# Generated by Django 4.1.7 on 2023-03-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_source_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='logo',
            field=models.FileField(default='settings.MEDIA_ROOT/avatars/1/Crying_Cat.jpg', upload_to='sources_logos/'),
        ),
    ]
