# Generated by Django 4.1.7 on 2023-03-28 15:12

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_alter_source_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='buy',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message="Exchange rate can't be smaller than zero")]),
        ),
        migrations.AlterField(
            model_name='rate',
            name='sell',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message="Exchange rate can't be smaller than zero")]),
        ),
        migrations.AlterField(
            model_name='source',
            name='logo',
            field=models.FileField(default='sources_logos/source-default.svg', upload_to='sources_logos/'),
        ),
    ]
