# Generated by Django 4.1.7 on 2023-04-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_alter_rate_buy_alter_rate_sell_alter_source_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rate',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='source',
            name='code_name',
            field=models.CharField(default='privatbank', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
