# Generated by Django 4.1.7 on 2023-04-12 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_alter_rate_options_source_code_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ('-created',), 'verbose_name_plural': 'emails'},
        ),
    ]
