# Generated by Django 4.1.7 on 2023-03-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_requestresponselog'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestresponselog',
            name='time',
            field=models.FloatField(default=0.0003),
            preserve_default=False,
        ),
    ]
