# Generated by Django 4.1.7 on 2023-03-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0008_requestresponselog_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestresponselog',
            name='request',
            field=models.CharField(max_length=16),
        ),
    ]
